# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  secret_key_base: d684dadef6934ec726d26c4ea1d4b75dd734a9c4f777e5869cb60620694fe657f6fbb6cac21c48769f0ef92d2fd7f0e7445500d838a2837f121e5421c020981f

test:
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  secret_key_base: ebd3cafb5e57ce2a3d3c5bf958c3c261166b9f62ba86e6390a4cce8efc873e2db32f97cd3ee824d62decaff35fe31832aac4eb7263f436d50bdbf830a579cac9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
